version: 2.1
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: Git restore cache
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run:
          name: Fetch git tags
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: Compress git objects
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  npm_install:
    description: "Install npm modules"
    steps:
      - restore_cache:
          name: Restore npm cache
          keys:
            - npm-v1-{{ checksum "package.json" }}
            - npm-v1-
      - run:
          name: Install npm modules
          command: npm i
      - save_cache:
          name: Save NPM cache
          key: npm-v1-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  build:
    description: "Build"
    steps:
      - run:
          name: "Gulp build"
          command: node_modules/gulp/bin/gulp.js build-min
  deploy:
    description: "Deploy to k8s cluster"
    parameters:
      target:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: www
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages@2.0.1
            git config user.email "ci-build@binary.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist www
      - add_ssh_keys:
          fingerprints:
            - "05:63:10:5c:ac:4d:8a:83:14:36:ba:41:d8:6c:5a:52"
      - run:
          name: Deploying to GitHub
          command: echo << parameters.target >>

  npm_test:
    description: Run test
    steps:
      - run:
          name: Run tests
          command: |
            for i in {1..3}; do npm test && break; done

jobs:
  test:
    docker:
      - image: circleci/node:8.10.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - npm_test

  release_beta:
    docker:
      - image: circleci/node:8.10.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - build
      - deploy:
          target: "staging"

  release_production:
    docker:
      - image: circleci/node:8.10.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install
      - build
      - deploy:
          target: "production"

workflows:
  test:
    jobs:
      - test
  release:
    jobs:
      - release_beta:
          filters:
            branches:
              only: /^master$/
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
